#!/usr/bin/env ansible-playbook
---
- hosts: timing_board_controller
  roles:
    - default
  vars:
    deploy_dir: "{{ ansible_user_dir }}/screen-timing-board"
    deploy_files:
      - "{{ main_script }}"
      - logo.png
    main_script: timing_board.py
