---
- name: install required packages
  become: yes
  apt:
    name: "{{ packages }}"
    install_recommends: no
    state: present
    update_cache: yes

- name: copy files to deploy
  copy:
    src: "{{ item }}"
    dest: "{{ deploy_dir }}/"
  loop: "{{ deploy_files }}"

- name: write .xsession file
  template:
    src: .xsession.j2
    dest: "{{ ansible_user_dir }}/.xsession"
    force: yes
